---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xnamespaces.example.crossplane.io
spec:
  group: example.crossplane.io
  names:
    kind: XNamespace
    plural: xnamespaces
  claimNames:
    kind: NamespaceClaim
    plural: namespaceclaims
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              namespaceName:
                type: string
                description: Nome do namespace a ser criado
              labels:
                type: object
                additionalProperties:
                  type: string
                description: Labels para o namespace
            required:
            - namespaceName
