---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-dev
  labels:
    environment: development
    managed-by: demo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: demo-dev
data:
  database_url: "postgres://localhost:5432/myapp"
  app_env: "development"
